server:
  port: 81

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true # 不注册进eureka服务中心
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka  #集群版
